travis:
  secure:
    BINSTAR_TOKEN: UB4BtIR4ng71pUvYh8CtuRo9X6dET8AeibVrTLl0RyB5W5TarHBzcLK81/1XelpQ5tPc76NX8ENXLEkufM/3tsuHSvgRrQC2kjrl+DQH65Hvut6Zh4IdtRKgITXGsCsP6I8g1Aq335uqfIjMuu8ZRn3y2xfZIlsm5eG1y1+5G7hr4PAdrZzJYChTz/LHzxrFuqg/wDY4HDb+iNbB/n/YnxOyPzbgghs4XM4jqB1in81yCSV9bNoTQvYYQxrZJbpzRAC2m3lLfFHgo8chxGDRInhi0/esc5nZvjuLzyj9mNYzB7s7Z3fPntY5Nhgt/8X+zIJRsUUpzGtiyhHYm83y//K/SS1jfbsuYyWgWedua2Zi1PC0bQfutYkQNujqYsDloVVKPwFY8fIv0U0j8wwC4yrZ3b9bUZcoCTDzrqzYQlLrXnNYt1BsCPUBdlVZIGhH4Pr1QOIcjDK/sE4wBllnFe4wYJyvZ/LYtBG0QzqCXVtvwvldeZkA0epsNs0PdBmdto5K1UvXT+WpaSPS8/LYeaHD0E878fDg7gL5LNsJjrqnFN1WCvwE+EOZLHlpmWUYRD3NIkfjFyYG4DQ0tVKVL8jOV6y59Dkqh2ZD3Wx90qgtcC8Fb6mglYey2QSbG1/hfxXgVKAYNswmamXgF/NbDtaT8NNOzXgTn1hZ+uERz2A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
